apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aiaad-keyvault-spc
  namespace: aiaad-platform
spec:
  provider: azure
  secretObjects:
    - secretName: openai-service-account
      type: Opaque
      data:
        - objectName: openai-service-account
          key: OPENAI_API_KEY
    - secretName: aiaad-neo4j-credentials
      type: Opaque
      data:
        - objectName: aiaad-neo4j-password
          key: NEO4J_PASSWORD
    - secretName: aiaad-ado-credentials
      type: Opaque
      data:
        - objectName: aiaad-ado-pat
          key: ADO_PAT
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d3792240-0d7b-42b0-a8fd-e08a4163e4ec"
    keyvaultName: "kv-jbluejipmztn4"
    objects: |
      array:
        - |
          objectName: openai-service-account
          objectType: secret
        - |
          objectName: aiaad-neo4j-password
          objectType: secret
        - |
          objectName: aiaad-ado-pat
          objectType: secret
    tenantId: "821e7efe-4ccd-4c7f-a717-31bd85305b4e"
