apiVersion: v1
kind: Service
metadata:
  name: aiaad-kafka-controller-headless
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: aiaad-kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-controller
      port: 9093
      targetPort: 9093
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: aiaad-kafka
